name: annuityleads
favicon: null
layout_spectrum: 0.29105888423509896
typography_spectrum: 0.5692777016665787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7323613043408841
  lightness: 0.11249190336093307
  saturation: 0.13602717476896942
  rhythmicContrast: 0.7701370040886104
purpose: []
