name: annuityleads
favicon: null
layout_spectrum: 0.51341
typography_spectrum: 0.78891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#0055aa'
    - '#9596b5'
    - '#00ffff'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
